# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: map_road.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import map.map_geometry_pb2 as map__geometry__pb2
import map.map_id_pb2 as map__id__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='map_road.proto',
  package='apollo.hdmap',
  syntax='proto2',
  serialized_pb=_b('\n\x0emap_road.proto\x12\x0c\x61pollo.hdmap\x1a\x12map_geometry.proto\x1a\x0cmap_id.proto\"\xa9\x01\n\x0c\x42oundaryEdge\x12\"\n\x05\x63urve\x18\x01 \x01(\x0b\x32\x13.apollo.hdmap.Curve\x12-\n\x04type\x18\x02 \x01(\x0e\x32\x1f.apollo.hdmap.BoundaryEdge.Type\"F\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06NORMAL\x10\x01\x12\x11\n\rLEFT_BOUNDARY\x10\x02\x12\x12\n\x0eRIGHT_BOUNDARY\x10\x03\";\n\x0f\x42oundaryPolygon\x12(\n\x04\x65\x64ge\x18\x01 \x03(\x0b\x32\x1a.apollo.hdmap.BoundaryEdge\"q\n\x0cRoadBoundary\x12\x34\n\router_polygon\x18\x01 \x01(\x0b\x32\x1d.apollo.hdmap.BoundaryPolygon\x12+\n\x04hole\x18\x02 \x03(\x0b\x32\x1d.apollo.hdmap.BoundaryPolygon\"W\n\x0fRoadROIBoundary\x12\x0f\n\x02id\x18\x01 \x01(\x0b\x32\x03.Id\x12\x33\n\x0froad_boundaries\x18\x02 \x03(\x0b\x32\x1a.apollo.hdmap.RoadBoundary\"b\n\x0bRoadSection\x12\x0f\n\x02id\x18\x01 \x01(\x0b\x32\x03.Id\x12\x14\n\x07lane_id\x18\x02 \x03(\x0b\x32\x03.Id\x12,\n\x08\x62oundary\x18\x03 \x01(\x0b\x32\x1a.apollo.hdmap.RoadBoundary\"\x91\x01\n\x04Road\x12\x0f\n\x02id\x18\x01 \x01(\x0b\x32\x03.Id\x12*\n\x07section\x18\x02 \x03(\x0b\x32\x19.apollo.hdmap.RoadSection\x12\x18\n\x0bjunction_id\x18\x03 \x01(\x0b\x32\x03.Id\x12\x10\n\x08junction\x18\x04 \x01(\t\x12 \n\x04link\x18\x05 \x03(\x0b\x32\x12.apollo.hdmap.Link\"\x8c\x01\n\x04Link\x12.\n\x0bpredecessor\x18\x01 \x03(\x0b\x32\x19.apollo.hdmap.Predecessor\x12*\n\tsuccessor\x18\x02 \x03(\x0b\x32\x17.apollo.hdmap.Successor\x12(\n\x08neighbor\x18\x03 \x03(\x0b\x32\x16.apollo.hdmap.Neighbor\"P\n\x0bPredecessor\x12\x13\n\x0b\x65lementType\x18\x01 \x02(\t\x12\x16\n\telementId\x18\x02 \x02(\x0b\x32\x03.Id\x12\x14\n\x0c\x63ontactPoint\x18\x03 \x02(\t\"N\n\tSuccessor\x12\x13\n\x0b\x65lementType\x18\x01 \x02(\t\x12\x16\n\telementId\x18\x02 \x02(\x0b\x32\x03.Id\x12\x14\n\x0c\x63ontactPoint\x18\x03 \x02(\t\"C\n\x08Neighbor\x12\x0c\n\x04side\x18\x01 \x02(\t\x12\x16\n\telementId\x18\x02 \x02(\x0b\x32\x03.Id\x12\x11\n\tdirection\x18\x03 \x02(\t')
  ,
  dependencies=[map__geometry__pb2.DESCRIPTOR,map__id__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_BOUNDARYEDGE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='apollo.hdmap.BoundaryEdge.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NORMAL', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEFT_BOUNDARY', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIGHT_BOUNDARY', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=166,
  serialized_end=236,
)
_sym_db.RegisterEnumDescriptor(_BOUNDARYEDGE_TYPE)


_BOUNDARYEDGE = _descriptor.Descriptor(
  name='BoundaryEdge',
  full_name='apollo.hdmap.BoundaryEdge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='curve', full_name='apollo.hdmap.BoundaryEdge.curve', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='apollo.hdmap.BoundaryEdge.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BOUNDARYEDGE_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=236,
)


_BOUNDARYPOLYGON = _descriptor.Descriptor(
  name='BoundaryPolygon',
  full_name='apollo.hdmap.BoundaryPolygon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='edge', full_name='apollo.hdmap.BoundaryPolygon.edge', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=297,
)


_ROADBOUNDARY = _descriptor.Descriptor(
  name='RoadBoundary',
  full_name='apollo.hdmap.RoadBoundary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='outer_polygon', full_name='apollo.hdmap.RoadBoundary.outer_polygon', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hole', full_name='apollo.hdmap.RoadBoundary.hole', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=299,
  serialized_end=412,
)


_ROADROIBOUNDARY = _descriptor.Descriptor(
  name='RoadROIBoundary',
  full_name='apollo.hdmap.RoadROIBoundary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='apollo.hdmap.RoadROIBoundary.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='road_boundaries', full_name='apollo.hdmap.RoadROIBoundary.road_boundaries', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=414,
  serialized_end=501,
)


_ROADSECTION = _descriptor.Descriptor(
  name='RoadSection',
  full_name='apollo.hdmap.RoadSection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='apollo.hdmap.RoadSection.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lane_id', full_name='apollo.hdmap.RoadSection.lane_id', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='boundary', full_name='apollo.hdmap.RoadSection.boundary', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=503,
  serialized_end=601,
)


_ROAD = _descriptor.Descriptor(
  name='Road',
  full_name='apollo.hdmap.Road',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='apollo.hdmap.Road.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='section', full_name='apollo.hdmap.Road.section', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='junction_id', full_name='apollo.hdmap.Road.junction_id', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='junction', full_name='apollo.hdmap.Road.junction', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='link', full_name='apollo.hdmap.Road.link', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=604,
  serialized_end=749,
)


_LINK = _descriptor.Descriptor(
  name='Link',
  full_name='apollo.hdmap.Link',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='predecessor', full_name='apollo.hdmap.Link.predecessor', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='successor', full_name='apollo.hdmap.Link.successor', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='neighbor', full_name='apollo.hdmap.Link.neighbor', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=752,
  serialized_end=892,
)


_PREDECESSOR = _descriptor.Descriptor(
  name='Predecessor',
  full_name='apollo.hdmap.Predecessor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='elementType', full_name='apollo.hdmap.Predecessor.elementType', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='elementId', full_name='apollo.hdmap.Predecessor.elementId', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='contactPoint', full_name='apollo.hdmap.Predecessor.contactPoint', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=894,
  serialized_end=974,
)


_SUCCESSOR = _descriptor.Descriptor(
  name='Successor',
  full_name='apollo.hdmap.Successor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='elementType', full_name='apollo.hdmap.Successor.elementType', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='elementId', full_name='apollo.hdmap.Successor.elementId', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='contactPoint', full_name='apollo.hdmap.Successor.contactPoint', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=976,
  serialized_end=1054,
)


_NEIGHBOR = _descriptor.Descriptor(
  name='Neighbor',
  full_name='apollo.hdmap.Neighbor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='side', full_name='apollo.hdmap.Neighbor.side', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='elementId', full_name='apollo.hdmap.Neighbor.elementId', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='direction', full_name='apollo.hdmap.Neighbor.direction', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1056,
  serialized_end=1123,
)

_BOUNDARYEDGE.fields_by_name['curve'].message_type = map__geometry__pb2._CURVE
_BOUNDARYEDGE.fields_by_name['type'].enum_type = _BOUNDARYEDGE_TYPE
_BOUNDARYEDGE_TYPE.containing_type = _BOUNDARYEDGE
_BOUNDARYPOLYGON.fields_by_name['edge'].message_type = _BOUNDARYEDGE
_ROADBOUNDARY.fields_by_name['outer_polygon'].message_type = _BOUNDARYPOLYGON
_ROADBOUNDARY.fields_by_name['hole'].message_type = _BOUNDARYPOLYGON
_ROADROIBOUNDARY.fields_by_name['id'].message_type = map__id__pb2._ID
_ROADROIBOUNDARY.fields_by_name['road_boundaries'].message_type = _ROADBOUNDARY
_ROADSECTION.fields_by_name['id'].message_type = map__id__pb2._ID
_ROADSECTION.fields_by_name['lane_id'].message_type = map__id__pb2._ID
_ROADSECTION.fields_by_name['boundary'].message_type = _ROADBOUNDARY
_ROAD.fields_by_name['id'].message_type = map__id__pb2._ID
_ROAD.fields_by_name['section'].message_type = _ROADSECTION
_ROAD.fields_by_name['junction_id'].message_type = map__id__pb2._ID
_ROAD.fields_by_name['link'].message_type = _LINK
_LINK.fields_by_name['predecessor'].message_type = _PREDECESSOR
_LINK.fields_by_name['successor'].message_type = _SUCCESSOR
_LINK.fields_by_name['neighbor'].message_type = _NEIGHBOR
_PREDECESSOR.fields_by_name['elementId'].message_type = map__id__pb2._ID
_SUCCESSOR.fields_by_name['elementId'].message_type = map__id__pb2._ID
_NEIGHBOR.fields_by_name['elementId'].message_type = map__id__pb2._ID
DESCRIPTOR.message_types_by_name['BoundaryEdge'] = _BOUNDARYEDGE
DESCRIPTOR.message_types_by_name['BoundaryPolygon'] = _BOUNDARYPOLYGON
DESCRIPTOR.message_types_by_name['RoadBoundary'] = _ROADBOUNDARY
DESCRIPTOR.message_types_by_name['RoadROIBoundary'] = _ROADROIBOUNDARY
DESCRIPTOR.message_types_by_name['RoadSection'] = _ROADSECTION
DESCRIPTOR.message_types_by_name['Road'] = _ROAD
DESCRIPTOR.message_types_by_name['Link'] = _LINK
DESCRIPTOR.message_types_by_name['Predecessor'] = _PREDECESSOR
DESCRIPTOR.message_types_by_name['Successor'] = _SUCCESSOR
DESCRIPTOR.message_types_by_name['Neighbor'] = _NEIGHBOR

BoundaryEdge = _reflection.GeneratedProtocolMessageType('BoundaryEdge', (_message.Message,), dict(
  DESCRIPTOR = _BOUNDARYEDGE,
  __module__ = 'map_road_pb2'
  # @@protoc_insertion_point(class_scope:apollo.hdmap.BoundaryEdge)
  ))
_sym_db.RegisterMessage(BoundaryEdge)

BoundaryPolygon = _reflection.GeneratedProtocolMessageType('BoundaryPolygon', (_message.Message,), dict(
  DESCRIPTOR = _BOUNDARYPOLYGON,
  __module__ = 'map_road_pb2'
  # @@protoc_insertion_point(class_scope:apollo.hdmap.BoundaryPolygon)
  ))
_sym_db.RegisterMessage(BoundaryPolygon)

RoadBoundary = _reflection.GeneratedProtocolMessageType('RoadBoundary', (_message.Message,), dict(
  DESCRIPTOR = _ROADBOUNDARY,
  __module__ = 'map_road_pb2'
  # @@protoc_insertion_point(class_scope:apollo.hdmap.RoadBoundary)
  ))
_sym_db.RegisterMessage(RoadBoundary)

RoadROIBoundary = _reflection.GeneratedProtocolMessageType('RoadROIBoundary', (_message.Message,), dict(
  DESCRIPTOR = _ROADROIBOUNDARY,
  __module__ = 'map_road_pb2'
  # @@protoc_insertion_point(class_scope:apollo.hdmap.RoadROIBoundary)
  ))
_sym_db.RegisterMessage(RoadROIBoundary)

RoadSection = _reflection.GeneratedProtocolMessageType('RoadSection', (_message.Message,), dict(
  DESCRIPTOR = _ROADSECTION,
  __module__ = 'map_road_pb2'
  # @@protoc_insertion_point(class_scope:apollo.hdmap.RoadSection)
  ))
_sym_db.RegisterMessage(RoadSection)

Road = _reflection.GeneratedProtocolMessageType('Road', (_message.Message,), dict(
  DESCRIPTOR = _ROAD,
  __module__ = 'map_road_pb2'
  # @@protoc_insertion_point(class_scope:apollo.hdmap.Road)
  ))
_sym_db.RegisterMessage(Road)

Link = _reflection.GeneratedProtocolMessageType('Link', (_message.Message,), dict(
  DESCRIPTOR = _LINK,
  __module__ = 'map_road_pb2'
  # @@protoc_insertion_point(class_scope:apollo.hdmap.Link)
  ))
_sym_db.RegisterMessage(Link)

Predecessor = _reflection.GeneratedProtocolMessageType('Predecessor', (_message.Message,), dict(
  DESCRIPTOR = _PREDECESSOR,
  __module__ = 'map_road_pb2'
  # @@protoc_insertion_point(class_scope:apollo.hdmap.Predecessor)
  ))
_sym_db.RegisterMessage(Predecessor)

Successor = _reflection.GeneratedProtocolMessageType('Successor', (_message.Message,), dict(
  DESCRIPTOR = _SUCCESSOR,
  __module__ = 'map_road_pb2'
  # @@protoc_insertion_point(class_scope:apollo.hdmap.Successor)
  ))
_sym_db.RegisterMessage(Successor)

Neighbor = _reflection.GeneratedProtocolMessageType('Neighbor', (_message.Message,), dict(
  DESCRIPTOR = _NEIGHBOR,
  __module__ = 'map_road_pb2'
  # @@protoc_insertion_point(class_scope:apollo.hdmap.Neighbor)
  ))
_sym_db.RegisterMessage(Neighbor)


# @@protoc_insertion_point(module_scope)
