# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: map_junction.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import map.map_id_pb2 as map__id__pb2
import map.map_geometry_pb2 as map__geometry__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='map_junction.proto',
  package='apollo.hdmap',
  syntax='proto2',
  serialized_pb=_b('\n\x12map_junction.proto\x12\x0c\x61pollo.hdmap\x1a\x0cmap_id.proto\x1a\x12map_geometry.proto\"\xf0\x01\n\x08Junction\x12\x0f\n\x02id\x18\x01 \x01(\x0b\x32\x03.Id\x12&\n\x07polygon\x18\x02 \x01(\x0b\x32\x15.apollo.hdmap.Polygon\x12\x17\n\noverlap_id\x18\x03 \x03(\x0b\x32\x03.Id\x12,\n\nconnection\x18\x04 \x03(\x0b\x32\x18.apollo.hdmap.Connection\x12&\n\x07outline\x18\x05 \x03(\x0b\x32\x15.apollo.hdmap.Outline\x12<\n\x12objectOverlapGroup\x18\x06 \x03(\x0b\x32 .apollo.hdmap.ObjectOverlapGroup\"\x95\x01\n\nConnection\x12\x0f\n\x02id\x18\x01 \x02(\x0b\x32\x03.Id\x12\x19\n\x0cincomingRoad\x18\x02 \x01(\x0b\x32\x03.Id\x12\x1b\n\x0e\x63onnectingRoad\x18\x03 \x01(\x0b\x32\x03.Id\x12\x14\n\x0c\x63ontactPoint\x18\x04 \x01(\t\x12(\n\x08laneLink\x18\x05 \x03(\x0b\x32\x16.apollo.hdmap.LaneLink\"$\n\x08LaneLink\x12\x0c\n\x04\x66rom\x18\x01 \x02(\x05\x12\n\n\x02to\x18\x02 \x02(\x05\";\n\x07Outline\x12\x30\n\x0c\x63ornerGlobal\x18\x01 \x03(\x0b\x32\x1a.apollo.hdmap.CornerGlobal\"/\n\x0c\x43ornerGlobal\x12\t\n\x01x\x18\x01 \x02(\x01\x12\t\n\x01y\x18\x02 \x02(\x01\x12\t\n\x01z\x18\x03 \x02(\x01\"L\n\x12ObjectOverlapGroup\x12\x36\n\x0fobjectReference\x18\x01 \x03(\x0b\x32\x1d.apollo.hdmap.ObjectReference\"\"\n\x0fObjectReference\x12\x0f\n\x02id\x18\x01 \x02(\x0b\x32\x03.Id')
  ,
  dependencies=[map__id__pb2.DESCRIPTOR,map__geometry__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_JUNCTION = _descriptor.Descriptor(
  name='Junction',
  full_name='apollo.hdmap.Junction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='apollo.hdmap.Junction.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='polygon', full_name='apollo.hdmap.Junction.polygon', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='overlap_id', full_name='apollo.hdmap.Junction.overlap_id', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='connection', full_name='apollo.hdmap.Junction.connection', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='outline', full_name='apollo.hdmap.Junction.outline', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='objectOverlapGroup', full_name='apollo.hdmap.Junction.objectOverlapGroup', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=311,
)


_CONNECTION = _descriptor.Descriptor(
  name='Connection',
  full_name='apollo.hdmap.Connection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='apollo.hdmap.Connection.id', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='incomingRoad', full_name='apollo.hdmap.Connection.incomingRoad', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='connectingRoad', full_name='apollo.hdmap.Connection.connectingRoad', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='contactPoint', full_name='apollo.hdmap.Connection.contactPoint', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='laneLink', full_name='apollo.hdmap.Connection.laneLink', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=314,
  serialized_end=463,
)


_LANELINK = _descriptor.Descriptor(
  name='LaneLink',
  full_name='apollo.hdmap.LaneLink',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='from', full_name='apollo.hdmap.LaneLink.from', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='to', full_name='apollo.hdmap.LaneLink.to', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=465,
  serialized_end=501,
)


_OUTLINE = _descriptor.Descriptor(
  name='Outline',
  full_name='apollo.hdmap.Outline',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cornerGlobal', full_name='apollo.hdmap.Outline.cornerGlobal', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=503,
  serialized_end=562,
)


_CORNERGLOBAL = _descriptor.Descriptor(
  name='CornerGlobal',
  full_name='apollo.hdmap.CornerGlobal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='apollo.hdmap.CornerGlobal.x', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='apollo.hdmap.CornerGlobal.y', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z', full_name='apollo.hdmap.CornerGlobal.z', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=564,
  serialized_end=611,
)


_OBJECTOVERLAPGROUP = _descriptor.Descriptor(
  name='ObjectOverlapGroup',
  full_name='apollo.hdmap.ObjectOverlapGroup',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='objectReference', full_name='apollo.hdmap.ObjectOverlapGroup.objectReference', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=613,
  serialized_end=689,
)


_OBJECTREFERENCE = _descriptor.Descriptor(
  name='ObjectReference',
  full_name='apollo.hdmap.ObjectReference',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='apollo.hdmap.ObjectReference.id', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=691,
  serialized_end=725,
)

_JUNCTION.fields_by_name['id'].message_type = map__id__pb2._ID
_JUNCTION.fields_by_name['polygon'].message_type = map__geometry__pb2._POLYGON
_JUNCTION.fields_by_name['overlap_id'].message_type = map__id__pb2._ID
_JUNCTION.fields_by_name['connection'].message_type = _CONNECTION
_JUNCTION.fields_by_name['outline'].message_type = _OUTLINE
_JUNCTION.fields_by_name['objectOverlapGroup'].message_type = _OBJECTOVERLAPGROUP
_CONNECTION.fields_by_name['id'].message_type = map__id__pb2._ID
_CONNECTION.fields_by_name['incomingRoad'].message_type = map__id__pb2._ID
_CONNECTION.fields_by_name['connectingRoad'].message_type = map__id__pb2._ID
_CONNECTION.fields_by_name['laneLink'].message_type = _LANELINK
_OUTLINE.fields_by_name['cornerGlobal'].message_type = _CORNERGLOBAL
_OBJECTOVERLAPGROUP.fields_by_name['objectReference'].message_type = _OBJECTREFERENCE
_OBJECTREFERENCE.fields_by_name['id'].message_type = map__id__pb2._ID
DESCRIPTOR.message_types_by_name['Junction'] = _JUNCTION
DESCRIPTOR.message_types_by_name['Connection'] = _CONNECTION
DESCRIPTOR.message_types_by_name['LaneLink'] = _LANELINK
DESCRIPTOR.message_types_by_name['Outline'] = _OUTLINE
DESCRIPTOR.message_types_by_name['CornerGlobal'] = _CORNERGLOBAL
DESCRIPTOR.message_types_by_name['ObjectOverlapGroup'] = _OBJECTOVERLAPGROUP
DESCRIPTOR.message_types_by_name['ObjectReference'] = _OBJECTREFERENCE

Junction = _reflection.GeneratedProtocolMessageType('Junction', (_message.Message,), dict(
  DESCRIPTOR = _JUNCTION,
  __module__ = 'map_junction_pb2'
  # @@protoc_insertion_point(class_scope:apollo.hdmap.Junction)
  ))
_sym_db.RegisterMessage(Junction)

Connection = _reflection.GeneratedProtocolMessageType('Connection', (_message.Message,), dict(
  DESCRIPTOR = _CONNECTION,
  __module__ = 'map_junction_pb2'
  # @@protoc_insertion_point(class_scope:apollo.hdmap.Connection)
  ))
_sym_db.RegisterMessage(Connection)

LaneLink = _reflection.GeneratedProtocolMessageType('LaneLink', (_message.Message,), dict(
  DESCRIPTOR = _LANELINK,
  __module__ = 'map_junction_pb2'
  # @@protoc_insertion_point(class_scope:apollo.hdmap.LaneLink)
  ))
_sym_db.RegisterMessage(LaneLink)

Outline = _reflection.GeneratedProtocolMessageType('Outline', (_message.Message,), dict(
  DESCRIPTOR = _OUTLINE,
  __module__ = 'map_junction_pb2'
  # @@protoc_insertion_point(class_scope:apollo.hdmap.Outline)
  ))
_sym_db.RegisterMessage(Outline)

CornerGlobal = _reflection.GeneratedProtocolMessageType('CornerGlobal', (_message.Message,), dict(
  DESCRIPTOR = _CORNERGLOBAL,
  __module__ = 'map_junction_pb2'
  # @@protoc_insertion_point(class_scope:apollo.hdmap.CornerGlobal)
  ))
_sym_db.RegisterMessage(CornerGlobal)

ObjectOverlapGroup = _reflection.GeneratedProtocolMessageType('ObjectOverlapGroup', (_message.Message,), dict(
  DESCRIPTOR = _OBJECTOVERLAPGROUP,
  __module__ = 'map_junction_pb2'
  # @@protoc_insertion_point(class_scope:apollo.hdmap.ObjectOverlapGroup)
  ))
_sym_db.RegisterMessage(ObjectOverlapGroup)

ObjectReference = _reflection.GeneratedProtocolMessageType('ObjectReference', (_message.Message,), dict(
  DESCRIPTOR = _OBJECTREFERENCE,
  __module__ = 'map_junction_pb2'
  # @@protoc_insertion_point(class_scope:apollo.hdmap.ObjectReference)
  ))
_sym_db.RegisterMessage(ObjectReference)


# @@protoc_insertion_point(module_scope)
